version: "3.9"

services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2.7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  # app:
  #   build: .
  #   container_name: fastlinks
  #   restart: always
  #   depends_on:
  #     - db
  #     - redis
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - .env
  #   volumes:
  #     - .:/app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000

volumes:
  postgres_data:
