version: "3.7"
services:
  db:
    image: postgres:17
    container_name: db_app
    command: -p 5334
    expose:
      - 5334

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 6379
    expose:
      - 6379

  app:
    build:
      context: .
    container_name: fastlinks
    command: ["/fastlinks/docker/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db
      - redis
