version: "3.9"

services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5434"

  redis:
    image: redis:7.2.7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: fastlinks
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  postgres_data:
