version: "3.9"

services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis_cache
    command: --port 5370
    expose:
      - 5370

  app:
    build:
      context: .
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - postgres_db
      - redis_cache



# services:
#   db:
#     image: postgres:17
#     container_name: postgres_db
#     restart: always
#     environment:
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASS}
#       POSTGRES_DB: ${DB_NAME}
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     command: postgres_db -p 1221
#     ports:
#       - "5432:5432"

#   redis:
#     image: redis:7.2.7
#     container_name: redis_cache
#     restart: always
#     ports:
#       - "6379:6379"

#   app:
#     build: .
#     container_name: fastlinks
#     restart: always
#     depends_on:
#       - db
#       - redis
#     ports:
#       - "8000:8000"
#     env_file:
#       - .env
#     volumes:
#       - .:/app

# volumes:
#   postgres_data:
